sudo: required
language: python
python:
- '3.4'
- '3.5'
- '3.6'
- 3.7-dev

matrix:
  fast_finish: true

before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7638D0442B90D010
  - sudo apt-get install python-sip

install:
  - pip install coveralls lxml tox
  - python setup.py bdist_wheel
  - pip install --use-wheel ./dist/vulture_whitelist*.whl

script:
  - tox -e cleanup,py,docs,style,vulture

after_success:
  - coveralls
