sudo: required
language: python
python:
- '3.4'
- '3.5'
- '3.6'
- 3.7-dev

matrix:
  fast_finish: true

addons:
  apt:
    sources:
    - sourceline: "deb http://us.archive.ubuntu.com/ubuntu/ xenial main universe"
    packages:
    - sip-dev

install:
  - pip install coveralls lxml tox
  - python setup.py bdist_wheel
  - pip install --use-wheel ./dist/vulture_whitelist*.whl
script:
  - tox -e cleanup,py,docs,style,vulture
after_success:
  - coveralls
